"""Generates docs/checks.md from the check registry so the docs cannot drift from the code."""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from cspm.checks import all_checks  # noqa: E402

lines = [
    "# Check catalogue", "",
    "Generated by `tools/gen_docs.py` from the check registry; do not edit by hand.", "",
    "Framework references are indicative mappings to help with audit evidence, not a compliance "
    "assessment. CIS numbers refer to the CIS AWS Foundations Benchmark v3.0; confirm them against "
    "the benchmark version your organisation audits against.", "",
    "| ID | Service | Worst severity | Check | CIS AWS | ISO/IEC 27001:2022 | NIS2 |",
    "|---|---|---|---|---|---|---|",
]
for m, _ in all_checks():
    lines.append(f"| {m.id} | {m.service} | {m.severity} | {m.title} | {', '.join(m.cis)} | "
                 f"{', '.join(m.iso27001)} | {', '.join(m.nis2)} |")
for m, _ in all_checks():
    lines += ["", f"## {m.id}: {m.title}", "", m.description, "", f"**Fix:** {m.remediation}"]
(ROOT / "docs" / "checks.md").write_text("\n".join(lines) + "\n")
print("wrote docs/checks.md")
